#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : DeepSS docs  # The title of the book. Will be placed in the left navbar.
author                      : Jan Clemens  # The author of the book
copyright                   : "2020"  # Copyright year to be placed in the footer
# logo                        : logo.png  # A path to the book logo
execute:
  timeout: 300
  stderr_output: remove
  stdout_output: remove

parse:
  myst_extended_syntax: true

latex:
  latex_engine              : xelatex  # one of 'pdflatex', 'xelatex' (recommended for unicode), 'luatex', 'platex', 'uplatex'
