name: Python Package using Conda

on:
  push:
    paths-ignore: docs/**
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'manual run'  
        
jobs:
  build:
    name: test_cli (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-latest"]
#         os: ["ubuntu-latest", "macos-latest", "windows-latest"]
#         python-version: ["3.6", "3.7", "3.8"]
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
          activate-conda: true
      - name: Conda environment creation
        run: conda env create -n dss -f env/deepss_gui.yml
      - name: Install libsndfile (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get install libsndfile1
      - name: Test with pytest (Linux, Macos)
        if: runner.os != 'Windows'
        run: |
          source activate dss
          conda install pytest -n dss
          conda install pytest -n base
          python -m pytest
      - name: Test cli (Linux, Macos)
        if: runner.os != 'Windows'
        run: |
          source activate dss
          python -m dss.cli train --help
          dss train --help
          dss predict --help
          dss gui --help
      - name: Test with pytest (Windows)
        if: runner.os == 'Windows'
        run: |
          C:\Miniconda\condabin\conda.bat activate dss
          conda install pytest -n dss
          conda install pytest -n base
          python -m pytest
      - name: Test cli (Windows)
        if: runner.os == 'Windows'
        run: |
          C:\Miniconda\condabin\conda.bat activate dss
          python -m dss.cli train --help
          dss train --help
          dss predict --help
          dss gui --help
