name: Python Package using Conda

on: [push]

runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Test with pytest
        run: |
          conda install pytest
          $CONDA/bin/pytest


    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install package
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env create --file env/deepss_gui.yml --name base
    - name: Test with pytest
      run: |
        conda install pytest
        $CONDA/bin/pytest
    - name: Test cli
      run: |
        dss-train --help
        dss-predict --help
        xb --help
