name: Python Package using Conda

on:
  push:
    paths-ignore: docs/**

  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'manual run'  
        
jobs:
  build:
    name: test_cli (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: ["3.6", "3.7", "3.8"]
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: ${{ matrix.python-version }}
          conda-channels: anaconda, conda-forge
          activate-conda: true
      - run: conda --version
      - run: which python
      - name: Conda environment creation
        run: |
          conda env create -n dss -f env/deepss_gui.yml
      - name: install libsndfile
        if: runner.os == 'Linux'
        run: sudo apt-get install libsndfile1
      - name: Conda info
        run: conda info
      - name: Conda list
        run: conda list
      - name: Test with pytest
        if: runner.os != 'Linux'
        run: |
          source activate dss
          conda install pytest -n dss
          conda install pytest -n base
          python -m pytest
      - name: Test cli
        if: runner.os != 'Windows'
        run: |
          source activate dss
          python -m dss.cli train --help
          dss train --help
          dss predict --help
          dss gui --help
      - name: Test with pytest
        if: runner.os == 'Windows'
        run: |
          C:\Miniconda\Scripts\activate dss
          conda install pytest -n dss
          conda install pytest -n base
          python -m pytest
      - name: Test cli
        if: runner.os == 'Windows'
        run: |
          C:\Miniconda\Scripts\activate dss
          python -m dss.cli train --help
          dss train --help
          dss predict --help
          dss gui --help
